### ISSUE TITLE
finish is interrupt by ctrl-c

### ISSUE THREAD

**Issue by teawater** [teawater/cma#2]
tried 3 times, only got a traceback one time while press ctrl ^ C, the others got csv files successfully. The traceback should not be a big as we are debugging and we can try again. I think you can mark this issue as fixed.  Thank you for your hard work!

The traceback attached below whatever:

Breakpoint 5, 0xb7e50260 in free () from /lib/i386-linux-gnu/libc.so.6

Continuing.

Breakpoint 5, 0xb7e50260 in free () from /lib/i386-linux-gnu/libc.so.6

^CTraceback (most recent call last):

  File "/root/cma.py", line 549, in <module>

```
breaks[r.group(1)].event()
```

  File "/root/cma.py", line 373, in event

```
gdb.execute("finish", False, True)
```

KeyboardInterrupt: Quit

(gdb) bt
#0  0xb7e50260 in free () from /lib/i386-linux-gnu/libc.so.6
#1  0xb7e18c3d in vfprintf () from /lib/i386-linux-gnu/libc.so.6
#2  0xb7e4026b in vsnprintf () from /lib/i386-linux-gnu/libc.so.6
#3  0xb7e22f43 in snprintf () from /lib/i386-linux-gnu/libc.so.6
#4  0x08064d97 in zmalloc_get_rss () at zmalloc.c:369
#5  0x0805d494 in serverCron (eventLoop=0x60037350, id=0, clientData=0x0) at redis.c:1029
#6  0x0805915e in processTimeEvents (eventLoop=0x60037350) at ae.c:311
#7  0x08059444 in aeProcessEvents (eventLoop=0x60037350, flags=3) at ae.c:423
#8  0x0805954f in aeMain (eventLoop=0x60037350) at ae.c:455
#9  0x08063314 in main (argc=1, argv=0xbffff2d4) at redis.c:3178

Leon

**Comment by teawater** [comment]
@leonumix

**Comment by teawater** [comment]
@leoumix
I just did some change on the signal handler of the cma.py to make it handle ctrl-c better.
And I tried it with redis-server.

Could you help me try it when you have time?

**Comment by leonumix** [comment]
Sure.

Leon

**Comment by leonumix** [comment]
I cannot reproduce the ctrl-c issue after applied the new fix and tried lots of times. 

cma.py looks excellent to me right now.

Thanks!

Leon

**Comment by teawater** [comment]
That is great!  Thanks!
